version: '3.4'

services:
  postgresserver:
     image: postgres:latest
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 5432:5432
     environment:
         POSTGRES_PASSWORD: admin
     volumes:
       - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
